version: "3.7"
services:
  container:
    image: nginx   
    volumes:
      - ./container/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./container/index.html:/data/index.html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  app1:
    image: nginx   
    volumes:
      - ./app1/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app1/index.html:/data/index.html
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  
  app2:
    image: nginx   
    volumes:
      - ./app2/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app2/index.html:/data/index.html
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80