version: "3.7"
services:
  container:
    image: nginx   
    volumes:
      - ./container/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./container/index.html:/usr/share/nginx/html/container/index.html
      - ./app1/index.html:/usr/share/nginx/html/app1/index.html
      - ./app2/index.html:/usr/share/nginx/html/app2/index.html
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80